# Generated by Django 4.2 on 2023-04-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
