# Generated by Django 4.2 on 2023-04-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
