# Generated by Django 4.1.7 on 2023-04-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_postdb_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomments',
            old_name='user',
            new_name='commenter',
        ),
    ]
